env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1 # Skip downloading during yarn install
  PLAYWRIGHT_BROWSERS_PATH: 0 # Places binaries to node_modules/@playwright/test

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
            npx playwright install-deps

      - name: Setup
        run: |
            npm install
            npx playwright install
